description: A task runner / simpler Make alternative written in Go
downloadURLTemplate: https://github.com/go-{{.Name}}/{{.Name}}/releases/download/v{{.Version}}/{{.Name}}_{{.OS}}_{{.Arch}}.tar.gz
homepage: https://taskfile.dev/
versionArgs: [--version]
