description: Portable command-line YAML processor
downloadURLTemplate: https://github.com/mikefarah/{{.Name}}/releases/download/v{{.Version}}/{{.Name}}_{{.OS}}_{{.Arch}}.tar.gz
homepage: https://mikefarah.gitbook.io/yq/
ignoredVersions:
  - '4.17.1' # withdrawn
  - '4.24.1' # withdrawn
  - '4.24.3' # wrong version information
versionArgs: [--version]
