description: The official CLI for Amazon EKS
downloadURLTemplate: https://github.com/weaveworks/{{.Name}}/releases/download/v{{.Version}}/{{.Name}}_{{.OS | Title}}_{{.Arch}}.tar.gz
homepage: https://eksctl.io/
versionArgs: [version]
