description: Manage your database schema as code
downloadURLTemplate: https://release.ariga.io/atlas/atlas-community-{{.OS}}-{{.Arch}}-v{{.Version}}
homepage: https://atlasgo.io
versionArgs: [version]
