description: Visualize your multi-stage Dockerfiles
downloadURLTemplate: https://github.com/patrickhoefler/{{.Name}}/releases/download/v{{.Version}}/{{.Name}}_{{.Version}}_{{.OS}}_{{.Arch}}.tar.gz
homepage: https://github.com/patrickhoefler/dockerfilegraph
versionArgs: [--version]
