description: Fast disk usage analyzer with console interface written in Go
downloadURLTemplate: https://github.com/dundee/{{.Name}}/releases/download/v{{.Version}}/{{.Name}}_{{.OS}}_{{.Arch}}.tgz
homepage: https://github.com/dundee/gdu
ignoredVersions: ['4.3.3', '4.6.4']
versionArgs: [--version]
