tools:
  - age
  - age-keygen
  - air
  - atlas
  - chezmoi
  - cloudflared
  - dive
  - dockerfilegraph
  - eksctl
  - gdu
  - gh
  - godolint
  - golangci-lint
  - goreleaser
  - gping
  - grype
  - helm
  - hugo
  - k9s
  - kind
  - kompose
  - kops
  - kubectl
  - kubectx
  - kubefwd
  - kubens
  - kuberlr
  - kustomize
  - minikube
  - mise
  - pulumi
  - skaffold
  - sops
  - stern
  - syft
  - task
  - terraform
  - tkn
  - toolctl
  - yq
