tools:
  - age
  - chezmoi
  - dive
  - gh
  - golangci-lint
  - helm
  - k9s
  - kubectl
  - kubectx
  - kubefwd
  - kubens
  - kuberlr
  - kustomize
  - minikube
  - sops
  - stern
  - terraform
  - tkn
  - toolctl
  - yq
