description: A simple, modern and secure encryption tool
downloadURLTemplate: https://github.com/FiloSottile/age/releases/download/v{{.Version}}/age-v{{.Version}}-{{.OS}}-{{.Arch}}.tar.gz
homepage: https://age-encryption.org/
versionArgs: [--version]
