description: A tool for exploring each layer in a docker image
downloadURLTemplate: https://github.com/wagoodman/{{.Name}}/releases/download/v{{.Version}}/{{.Name}}_{{.Version}}_{{.OS}}_{{.Arch}}.tar.gz
homepage: https://github.com/wagoodman/dive
versionArgs: [version]
