description: Live reload for Go apps
downloadURLTemplate: https://github.com/cosmtrek/{{.Name}}/releases/download/v{{.Version}}/{{.Name}}_{{.Version}}_{{.OS}}_{{.Arch}}.tar.gz
homepage: https://github.com/cosmtrek/air
ignoredVersions:
  - 1.31.0 # never released
  - 1.32.0 # never released
  - 1.33.0 # never released
  - 1.34.0 # never released
  - 1.35.0 # never released
  - 1.36.0 # never released
  - 1.37.0 # never released
  - 1.38.0 # never released
  - 1.39.0 # never released
  - 1.53.0 # never released
  - 1.54.0 # never released
  - 1.55.0 # never released
  - 1.56.0 # never released
  - 1.57.0 # never released
  - 1.58.0 # never released
  - 1.59.0 # never released
versionArgs: [-v]
