description: The Kubernetes command-line tool
downloadURLTemplate: https://dl.k8s.io/release/v{{.Version}}/bin/{{.OS}}/{{.Arch}}/{{.Name}}
homepage: https://kubernetes.io/docs/reference/kubectl/
versionArgs: [version, --client, --short]
