description: The world's fastest framework for building websites
downloadURLTemplate: https://github.com/gohugoio/{{.Name}}/releases/download/v{{.Version}}/{{.Name}}_{{.Version}}_{{.OS}}-{{.Arch | DarwinArchUniversal}}.tar.gz
homepage: https://gohugo.io/
versionArgs: [version]
