description: The world's fastest framework for building websites
downloadURLTemplate: https://github.com/gohugoio/{{.Name}}/releases/download/v{{.Version}}/{{.Name}}_{{.Version}}_{{.OS | DarwinMacOS | LinuxTitle}}-{{.Arch | AMD64Bit | ARMUpper}}.tar.gz
homepage: https://gohugo.io/
versionArgs: [version]
