description: Infrastructure as code software tool
downloadURLTemplate: https://releases.hashicorp.com/{{.Name}}/{{.Version}}/{{.Name}}_{{.Version}}_{{.OS}}_{{.Arch}}.zip
homepage: https://www.terraform.io/
versionArgs: [version]
