description: Ping, but with a graph
downloadURLTemplate: https://github.com/orf/{{.Name}}/releases/download/{{.Name}}-v{{.Version}}/{{.Name}}-{{.OS | DarwinMacOS | LinuxTitleGnu |  }}-{{.Arch | AMD64X86_64}}.tar.gz
homepage: https://github.com/orf/gping
ignoredVersions:
  - '1.9.0'
  - '1.10.0'
  - '1.18.0' # Darwin x86_64 corrupted
versionArgs: [--version]
