description: A vulnerability scanner for container images and filesystems
downloadURLTemplate: https://github.com/anchore/{{.Name}}/releases/download/v{{.Version}}/{{.Name}}_{{.Version}}_{{.OS}}_{{.Arch}}.tar.gz
homepage: https://github.com/anchore/grype
versionArgs: [version]
ignoredVersions:
  - 0.74.5 # broken version output