description: The tool to control your tools
downloadURLTemplate: https://github.com/{{.Name}}/{{.Name}}/releases/download/v{{.Version}}/{{.Name}}_{{.Version}}_{{.OS}}_{{.Arch}}.tar.gz
homepage: https://github.com/toolctl/toolctl
versionArgs: [version, --short]
