description: Control your tools
downloadURLTemplate: https://github.com/{{.Name}}/{{.Name}}/releases/download/v{{.Version}}/{{.Name}}-{{.OS}}-{{.Arch}}.tar.gz
homepage: https://github.com/toolctl/toolctl
versionArgs: [version, --short]
